server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 010498
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

token:
  expirationms: 3600000
  secret:
    key: 48a868a4042f634ac04a117f00a87202131dd7c46c4b32c4acb3edc5e15f4511
